Services:
  starwars:
    URL: "https://swapi.dev/api"
    Protocol: "HTTPS"
    Plugins:
      - "rate-limit"
      - "logger"
      - "cache"
      - "cors"
    Endpoints:
      - Name: "List People"
        HTTPMethod: "GET"
        Path: "/people"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "Get Person"
        HTTPMethod: "GET"
        Path: "/people/{id}"
        Auth:
          ApplyAuth: false

      - Name: "List Starships"
        HTTPMethod: "GET"
        Path: "/starships"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "Get Starship"
        HTTPMethod: "GET"
        Path: "/starships/{id}"
        Auth:
          ApplyAuth: false
