openapi: 3.0.3
info:
  title: My API Gateway
  description: This is a sample service for the API gateway.
  version: 1.0.0
  termsOfService: "http://example.com/terms/"
  contact:
    name: API Support
    url: "http://example.com/support"
    email: support@example.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https://api.example.com/v1"
    description: Production server

paths:
  /tests:
    get:
      summary: List all tests
      operationId: listtests
      tags:
        - tests
      responses:
        "200":
          description: A list of tests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Test"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a new Test
      operationId: createTest
      tags:
        - tests
      requestBody:
        description: The Test to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
      responses:
        "201":
          description: Test created
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tests/{TestId}:
    parameters:
      - name: TestId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a single Test
      operationId: getTest
      tags:
        - tests
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"
        "404":
          description: Test not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Update an existing Test
      operationId: updateTest
      tags:
        - tests
      requestBody:
        description: Test data to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
      responses:
        "200":
          description: Test updated
        "400":
          description: Invalid input
        "404":
          description: Test not found
    delete:
      summary: Delete a Test
      operationId: deleteTest
      tags:
        - tests
      responses:
        "204":
          description: Test deleted
        "404":
          description: Test not found

components:
  schemas:
    Test:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier for a Test
        name:
          type: string
          description: Name of the Test
        description:
          type: string
          description: Detailed description of the Test
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

security:
  - api_key: []

securitySchemes:
  api_key:
    type: apiKey
    name: "X-API-KEY"
    in: header

tags:
  - name: tests
    description: Operations related to tests
