Plugins:
  LoggerConfig:
    FilePath: "./server.log"
    ErrOutput: "stderr"
  JWTConfig:
    SecretKey: "your-256-bit-secret"
    SigningMethod: "HS256"
    Issuer: "ExampleIssuer"
    Audience: "ExampleAudience"
    Scope: "ExampleScope"
  RateLimitConfig:
    Limit: 100
    Window: 1m
  CORSConfig:
    Origins: "*"
    Methods: "GET, POST, PUT, DELETE, OPTIONS"
    Headers: "Content-Type, Authorization"

Services:
  starwars:
    URL: "https://swapi.dev"
    Subpath: "/api"
    Protocol: "HTTP"
    Plugins:
      - "logger"
      - "cors"
      - "rate-limit"
      - "cache"
    Endpoints:
      - Name: "List People"
        HTTPMethod: "GET"
        Path: "/people"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "Get Person"
        HTTPMethod: "GET"
        Path: "/people/{id}"
        Auth:
          ApplyAuth: false

      - Name: "List Starships"
        HTTPMethod: "GET"
        Path: "/starships"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "Get Starship"
        HTTPMethod: "GET"
        Path: "/starships/{id}"
        Auth:
          ApplyAuth: false

  someotherserver:
    URL: "http://localhost:3001"
    Subpath: "/api"
    Protocol: "HTTP"
    Plugins:
      - "logger"
    Endpoints:
      - Name: "List People"
        HTTPMethod: "GET"
        Path: "/worlds"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "List People"
        HTTPMethod: "POST"
        Path: "/worlds"
        QueryParams:
          - Key: "page"
            Value: "1"
        Auth:
          ApplyAuth: false

      - Name: "Get Person"
        HTTPMethod: "GET"
        Path: "/worlds/{id}"
        Auth:
          ApplyAuth: false
